[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.75
    capsule = false
    capsule_fill = "outline"
    center = [ "clock" ]
    color = "tertiary"
    end = [
        "media",
        "tray",
        "notifications",
        "clipboard",
        "network",
        "bluetooth",
        "volume",
        "brightness",
        "battery",
        "control-center",
        "session"
    ]
    font_weight = 700
    icon_color = "secondary"
    margin_edge = 0
    margin_ends = 0
    padding = 12
    position = "top"
    radius = 0
    reserve_space = true
    shadow = false
    start = [ "launcher", "wallpaper", "workspaces" ]
    thickness = 34
    widget_spacing = 15

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 574.4000244140625
    output = "LVDS-1"
    placement_height = 720.0
    placement_width = 1280.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
border = false

[shell]
app_icon_colorize = true
font_family = "JetBrains Mono"
password_style = "random"
polkit_agent = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.panel]
    borders = true
    control_center_placement = "floating"
    launcher_placement = "floating"
    session_placement = "floating"
    shadow = false
    transparency_mode = "soft"
    wallpaper_placement = "floating"

[theme]
# builtin = "Rosé Pine"
# community_palette = "Paradise"
mode = "dark"
source = "wallpaper"
# source = "community"
pure_black_dark = false
# wallpaper_scheme = "m3-rainbow"
wallpaper_scheme = "muted"

    [theme.templates]
    builtin_ids = [ "btop", "foot", "gtk3", "gtk4", "helix", "hyprland", "kcolorscheme", "qt", "starship" ]
    community_ids = [ "pi-agent", "brave", "discord", "vscode", "zed", "steam", "bat", "herdr", "lazygit", "yazi" ]

[wallpaper]
path = "/home/zibbble/Pictures/Wallpapers"

    [wallpaper.automation]
    enabled = true
    interval_seconds = 300

    [wallpaper.default]
    path = "/home/zibbble/Pictures/Wallpapers/dark-waves.jpg"

    [wallpaper.last]
    path = "/home/zibbble/Pictures/Wallpapers/dark-waves.jpg"

    [wallpaper.monitors.LVDS-1]
    path = "/home/zibbble/Pictures/Wallpapers/dark-waves.jpg"

[widget.media]
enabled = false

[widget.workspaces]
hide_when_empty = false
label_source = "name"
max_label_chars = 8
