name = Trapped in Amber

ghostty = Retro
kitty   = Trapped in Amber
wezterm = Retro
gtk     = Orchis-Orange-Dark
icons   = Colloid-Orange-Dark

wallpaper = debdino.png

dunst_frame_global       = #f0a020

dunst_bg_low             = #0a1017
dunst_fg_low             = #f0a020
dunst_frame_low          = #f0a020
dunst_highlight_low      = #f0a020

dunst_bg_normal          = #0a1017
dunst_fg_normal          = #f0a020
dunst_frame_normal       = #f0a020
dunst_highlight_normal   = #ffc940

dunst_bg_critical        = #2a1810
dunst_fg_critical        = #f0a020
dunst_frame_critical     = #e05c1c
dunst_highlight_critical = #e05c1c
