accent = "#98b0b3"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#2a3132"
selection_bg = "#343b3d"
surface0 = "#2a3132"
surface1 = "#343b3d"
surface_dim = "#131616"
overlay0 = "#646b6c"
overlay1 = "#b0b4b5"
text = "#f2f3f3"
subtext0 = "#b0b4b5"
mauve = "#b6c7c9"
green = "#98b0b3"
yellow = "#8d9ca5"
red = "#fd4663"
blue = "#8f97a3"
teal = "#b8c1c7"
peach = "#fd8446"
