accent = "#a6a6a6"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#322a2a"
selection_bg = "#3d3434"
surface0 = "#322a2a"
surface1 = "#3d3434"
surface_dim = "#161313"
overlay0 = "#6d6666"
overlay1 = "#b5b0b0"
text = "#f3f2f2"
subtext0 = "#b5b0b0"
mauve = "#bfbfbf"
green = "#a6a6a6"
yellow = "#999999"
red = "#fd4663"
blue = "#999999"
teal = "#bfbfbf"
peach = "#fd8446"
