name = Rose Pine Moon

ghostty = Rose Pine Moon
kitty   = Rosé Pine Moon
wezterm = rose-pine-moon
gtk     = Orchis-Purple-Dark
icons   = Colloid-Catppuccin-Dark

wallpaper = wallhaven-85erok_3440x1440.png

dunst_frame_global       = #9ccfd8

dunst_bg_low             = #1f1d2e
dunst_fg_low             = #9ccfd8
dunst_frame_low          = #9ccfd8
dunst_highlight_low      = #9ccfd8

dunst_bg_normal          = #1f1d2e
dunst_fg_normal          = #e0def4
dunst_frame_normal       = #9ccfd8
dunst_highlight_normal   = #908caa

dunst_bg_critical        = #391f2b
dunst_fg_critical        = #e0def4
dunst_frame_critical     = #f6c177
dunst_highlight_critical = #f6c177
